### ISSUE TITLE
move plasmoid to home instead of root direcory

### ISSUE THREAD

**Issue by aadityapageni** [samirgaire10/com.samirgaire10.perplexityAi-plasma6#1]
1. in ReadMe, you could change 

> move the folder to /usr/share/plasma/plasmoids/ !!! sudo is required !!!

to
> move the folder to ~/.local/share/plasma/plasmoids

root is not required

2. could remove url bar and nav arrows for cleaner look
3. increase default widget height

**Comment by samirgaire10** [comment]
ok

**Comment by samirgaire10** [comment]
read me changed ,
other i will do it later !! tho when i have time  
u can now download from  
https://www.pling.com/member/767099/products/


https://www.pling.com/p/2151962/

**Comment by samirgaire10** [comment]
root is not required  \-- done 
could remove url bar and nav arrows for cleaner look --- removed
increase default widget height    -- height 100% and width 40   // done     


thank you -- bye
