### ISSUE TITLE
plasma 6: unable to install from plasmoid store, manuel download also dont working, system warning, old version plasmoid.

### ISSUE THREAD

**Issue by Pen-Man** [samirgaire10/com.samirgaire10.perplexityAi-plasma6#2]
unable to install from plasmoid store, manuel download also dont working, system warning, old version plasmoid.

**Comment by samirgaire10** [comment]
run  this;;;;;;;;;;;;

 git clone https://github.com/samirgaire10/com.samirgaire10.perplexityAi-plasma6.git

move the folder to .local/share/plasma/plasmoids/

**Comment by samirgaire10** [comment]
I think u could able to install from plasmoid store by now


manuel download also dont working
git clone https://github.com/samirgaire10/com.samirgaire10.perplexityAi-plasma6.git

move the folder to .local/share/plasma/plasmoids/

so i will close this  issuse
